// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attributes/{attribute_id}": {
            "get": {
                "description": "Get detailed information about a specific attribute definition using its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attributes"
                ],
                "summary": "Get a specific attribute definition by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attribute Definition ID (UUID)",
                        "name": "attribute_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved attribute definition",
                        "schema": {
                            "$ref": "#/definitions/models.AttributeDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Attribute definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing attribute definition's fields. EntityID cannot be changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attributes"
                ],
                "summary": "Update an existing attribute definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attribute Definition ID (UUID)",
                        "name": "attribute_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Attribute Definition fields to update",
                        "name": "attribute_definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateAttributeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated attribute definition",
                        "schema": {
                            "$ref": "#/definitions/models.AttributeDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Attribute definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an attribute definition by its UUID.",
                "tags": [
                    "attributes"
                ],
                "summary": "Delete an attribute definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attribute Definition ID (UUID)",
                        "name": "attribute_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted attribute definition"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Attribute definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/entities": {
            "get": {
                "description": "Get a list of all entity definitions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "List all entity definitions",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of entity definitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.EntityDefinition"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new entity definition with the provided name and description.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "Create a new entity definition",
                "parameters": [
                    {
                        "description": "Entity Definition to create",
                        "name": "entity_definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateEntityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created entity definition",
                        "schema": {
                            "$ref": "#/definitions/models.EntityDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/entities/{id}": {
            "get": {
                "description": "Get detailed information about a specific entity definition using its UUID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "Get a specific entity definition by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity Definition ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved entity definition",
                        "schema": {
                            "$ref": "#/definitions/models.EntityDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Entity definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing entity definition's name and/or description.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entities"
                ],
                "summary": "Update an existing entity definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity Definition ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Entity Definition fields to update",
                        "name": "entity_definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateEntityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated entity definition",
                        "schema": {
                            "$ref": "#/definitions/models.EntityDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Entity definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an entity definition by its UUID.",
                "tags": [
                    "entities"
                ],
                "summary": "Delete an entity definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity Definition ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted entity definition"
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Entity definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/entities/{id}/attributes": {
            "get": {
                "description": "Get a list of all attribute definitions associated with a given entity ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attributes"
                ],
                "summary": "List all attributes for a specific entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity ID (UUID)",
                        "name": "entity_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of attribute definitions",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.AttributeDefinition"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid Entity ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Entity definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new attribute definition for a specific entity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attributes"
                ],
                "summary": "Create a new attribute for an entity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Entity ID (UUID)",
                        "name": "entity_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Attribute Definition to create",
                        "name": "attribute_definition",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateAttributeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created attribute definition",
                        "schema": {
                            "$ref": "#/definitions/models.AttributeDefinition"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or Entity ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Entity definition not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error or unique constraint violation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AttributeDefinition": {
            "description": "AttributeDefinition represents the structure for an attribute definition.",
            "type": "object",
            "required": [
                "data_type",
                "entity_id",
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string",
                    "enum": [
                        "STRING",
                        "TEXT",
                        "INTEGER",
                        "FLOAT",
                        "BOOLEAN",
                        "DATETIME"
                    ]
                },
                "description": {
                    "type": "string"
                },
                "entity_id": {
                    "description": "Part of composite unique index",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_filterable": {
                    "type": "boolean"
                },
                "is_pii": {
                    "type": "boolean"
                },
                "name": {
                    "description": "Part of composite unique index",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.CreateAttributeRequest": {
            "type": "object",
            "required": [
                "data_type",
                "name"
            ],
            "properties": {
                "data_type": {
                    "type": "string",
                    "enum": [
                        "STRING",
                        "TEXT",
                        "INTEGER",
                        "FLOAT",
                        "BOOLEAN",
                        "DATETIME"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "is_filterable": {
                    "description": "Pointer to distinguish between false and not provided",
                    "type": "boolean"
                },
                "is_pii": {
                    "description": "Pointer to distinguish between false and not provided",
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "models.CreateEntityRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "models.EntityDefinition": {
            "description": "EntityDefinition represents the structure for an entity definition.",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AttributeDefinition"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.UpdateAttributeRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "enum": [
                        "STRING",
                        "TEXT",
                        "INTEGER",
                        "FLOAT",
                        "BOOLEAN",
                        "DATETIME"
                    ]
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "is_filterable": {
                    "type": "boolean"
                },
                "is_pii": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        },
        "models.UpdateEntityRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 1000
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Metadata Service API",
	Description:      "This is a sample server for a metadata service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
